@backend_HostAddress = http://localhost:5190
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjY5ZGJkYTdkZDA2YzQxY2IyNjM2ODJkMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFsZXhhbmRydWlhY29iMDFAZ21haWwuY29tIiwiZXhwIjoxNzc2MTA1MTI4LCJpc3MiOiJEZXZpY2VNYW5hZ2VtZW50QVBJIiwiYXVkIjoiRGV2aWNlTWFuYWdlbWVudENsaWVudCJ9.ReZuUBoE6Ek7Gy2rJrfof_2w2bHG3rcDVE7j467Wowk


POST {{backend_HostAddress}}/auth/login
content-Type: application/json
{
  "email": "alexandruiacob01@gmail.com",
  "password": "12345678"
}

###


GET {{backend_HostAddress}}/devices
Accept: application/json
Authorization: Bearer {{token}}
###

GET {{backend_HostAddress}}/devices/69d2f7e7c4f7a617d93682d4
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{backend_HostAddress}}/devices/
Content-Type: application/json
{
  "name": "iPhone 16",
  "manufacturer": "Apple",
  "type": "phone",
  "os": "iOS",
  "osVersion": "18.0",
  "processor": "A18",
  "ram": 8,
  "description": "Test device",
  "assignedUserId": null
}

###
DELETE {{backend_HostAddress}}/devices/69d44fa1005e7925ccf74955
Accept: application/json


###
GET {{backend_HostAddress}}/user
Accept: application/json


###
GET {{backend_HostAddress}}/user/69d2f7e7c4f7a617d93682d1


###
POST {{backend_HostAddress}}/auth/register
Content-Type: application/json

{
  "email": "alexiacob01@yahoo.com",
  "password": "1234567"
}

###

POST {{backend_HostAddress}}/auth/login
content-Type: application/json
{
  "email": "alexandruiacob01@gmail.com",
  "password": "12345678"
}

###
PUT {{backend_HostAddress}}/auth/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe",
  "role": "Developer",
  "location": "Cluj-Napoca"
}

###
POST {{backend_HostAddress}}/devices/69d2f7e7c4f7a617d93682d4/assign
Content-Type: application/json
Authorization: Bearer {{token}}